### ISSUE TITLE
Error on Web

### ISSUE THREAD

**Issue by odunboye** [DEVSOG12/flutter_paystack_payment#3]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/3253981/180608587-a24d1e7d-3bb8-4b88-83d4-f8e3bf97c382.png">

Kindly help resolve thank you

**Comment by DEVSOG12** [comment]
Sorry @odunboye, for the inconvenience. The reason for this issue on Flutter Web is because of the `CORS` setting on Paystack's API. However, as we wait till Paystack fixes this issue, they are a couple of workaround as [isssue](https://stackoverflow.com/questions/65630743/how-to-solve-flutter-web-api-cors-error-only-with-dart-code/66879350#66879350).

The first workaround is to disable web security but however this only works during testing and not in Production. 

The recommended workaround is run:
While testing: `flutter run -d chrome --web-renderer html`
To build for Production `flutter build web --web-renderer html.`

**Comment by odunboye** [comment]
Thank you so much for the response,  still getting the same error after trying the workaround

**Comment by DEVSOG12** [comment]
@odunboye Please confirm you tried the second workaround. 
1. Make sure you run flutter clean
2. Open up your terminal and run `flutter run -d chrome --web-renderer html`
3. If your building for production the remember to add the `--web-renderer`

I just tried it now and it's working fine. You can include your `flutter doctor -v`

**Comment by odunboye** [comment]
<img width="605" alt="image" src="https://user-images.githubusercontent.com/3253981/180640646-9a291b60-d06e-4b55-ac13-073fc41510d8.png">
<img width="733" alt="image" src="https://user-images.githubusercontent.com/3253981/180641436-9344d871-8ee8-4199-91ea-3f9e21e87909.png">
Same error using the example

**Comment by DEVSOG12** [comment]
@odunboye I have been able to reproduce your issue on your current Flutter Release. I'm looking into it and will get back to you soon. Thank you.

**Comment by odunboye** [comment]
@DEVSOG12 thank you for this package,  Please any luck with the fix?

**Comment by DEVSOG12** [comment]
@odunboye I have been trying various workaround but I haven't gotten a fixed solution. For now, I advise you to use the 1st workaround, it will work in development.

**Comment by DEVSOG12** [comment]
The Workaround

1- Go to `flutter\bin\cache` and remove a file named: `flutter_tools.stamp`

2- Go to `flutter\packages\flutter_tools\lib\src\web` and open the file `chrome.dart.`

3- Find `'--disable-extensions'`

4- Add `'--disable-web-security'`

**Comment by DEVSOG12** [comment]
@odunboye thank you for your patience. I have fixed the issue. Please upgrade to version `0.1.2+3`. Let me know if it works before I close this issue.

**Comment by odunboye** [comment]
Works now, Thank you so much!

**Comment by DEVSOG12** [comment]
Make sure it on the latest version. I noticed an issue with v0.1.2+1 kindly use the latest v0.1.2+3

**Comment by Princewil** [comment]
For web you can use this package => https://pub.dev/packages/flutter_paystack_plus

it supports other payment options like USSD, bank transfers etc
